-- 공지사항(TB_FXB_CMC008L) 데모 시드 — W1257S01 조회 테스트용. 대상='2'(전체공지), 최근 4일.
SET SERVEROUTPUT ON
DELETE FROM FXPL.TB_FXB_CMC008L WHERE FX_SYS_LSMD_ID='DEMOSEED';
INSERT INTO FXPL.TB_FXB_CMC008L (RGSN_YMD,PBNT_RGSN_SQN,RGSN_HMS,FX_PBNT_TTL_NM,PBNS_CON,PBNS_TGT_DCD,PBNT_TGT_ID,FX_PBNT_RGSR_NM,FX_SYS_LSMD_ID,FX_SYS_LSMD_TS)
  VALUES ('20260728',1,'090000','시스템 정기점검 안내','금일 23시부터 익일 01시까지 정기점검이 진행됩니다. 자세한 내용은 링크를 참고하세요.@URL:https://winway.co.kr/notice/1','2',NULL,'운영팀','DEMOSEED',SYSDATE);
INSERT INTO FXPL.TB_FXB_CMC008L (RGSN_YMD,PBNT_RGSN_SQN,RGSN_HMS,FX_PBNT_TTL_NM,PBNS_CON,PBNS_TGT_DCD,PBNT_TGT_ID,FX_PBNT_RGSR_NM,FX_SYS_LSMD_ID,FX_SYS_LSMD_TS)
  VALUES ('20260728',2,'101500','신규 통화쌍 추가 안내','EUR/KRW, JPY/KRW 등 신규 통화쌍이 추가되었습니다.','2',NULL,'운영팀','DEMOSEED',SYSDATE);
INSERT INTO FXPL.TB_FXB_CMC008L (RGSN_YMD,PBNT_RGSN_SQN,RGSN_HMS,FX_PBNT_TTL_NM,PBNS_CON,PBNS_TGT_DCD,PBNT_TGT_ID,FX_PBNT_RGSR_NM,FX_SYS_LSMD_ID,FX_SYS_LSMD_TS)
  VALUES ('20260727',1,'140000','거래시간 변경 공지','7월 27일부터 외환 거래시간이 확대됩니다.','2',NULL,'관리자','DEMOSEED',SYSDATE);
INSERT INTO FXPL.TB_FXB_CMC008L (RGSN_YMD,PBNT_RGSN_SQN,RGSN_HMS,FX_PBNT_TTL_NM,PBNS_CON,PBNS_TGT_DCD,PBNT_TGT_ID,FX_PBNT_RGSR_NM,FX_SYS_LSMD_ID,FX_SYS_LSMD_TS)
  VALUES ('20260726',1,'091000','마진 정책 변경 안내','고객 등급별 스프레드 정책이 일부 조정되었습니다.','2',NULL,'관리자','DEMOSEED',SYSDATE);
INSERT INTO FXPL.TB_FXB_CMC008L (RGSN_YMD,PBNT_RGSN_SQN,RGSN_HMS,FX_PBNT_TTL_NM,PBNS_CON,PBNS_TGT_DCD,PBNT_TGT_ID,FX_PBNT_RGSR_NM,FX_SYS_LSMD_ID,FX_SYS_LSMD_TS)
  VALUES ('20260725',1,'090000','WTG 서비스 오픈 공지','윈웨이 트레이딩 게이트웨이 서비스가 오픈되었습니다. 많은 이용 바랍니다.','2',NULL,'운영팀','DEMOSEED',SYSDATE);
COMMIT;
SELECT RGSN_YMD||' #'||PBNT_RGSN_SQN||' ['||PBNS_TGT_DCD||'] '||FX_PBNT_TTL_NM AS NOTICE FROM FXPL.TB_FXB_CMC008L WHERE FX_SYS_LSMD_ID='DEMOSEED' ORDER BY RGSN_YMD DESC, PBNT_RGSN_SQN DESC;
EXIT
