// WTG (Winway Trading Gateway) — Price stream service.
//
// Internal mci-price ↔ DMZ mci-edge-price 사이의 gRPC bidirectional stream.
// 시세 fan-out 의 핵심 통신 채널.
//
// 보안: mTLS gRPC (Phase 8 운영화 시점). DMZ → Internal 정방향만 정책상
// 허용되므로, edge 가 Internal 로 connect 하고 Internal 이 그 stream 으로
// tick 을 push 하는 reverse stream 패턴.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: wtg/v1/price.proto

package wtgpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceService_Subscribe_FullMethodName = "/wtg.v1.PriceService/Subscribe"
)

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PriceService 는 mci-price (Internal) 가 노출하는 gRPC 서비스다.
type PriceServiceClient interface {
	// Subscribe 는 edge 가 호출해서 Internal 로부터 tick stream 을 받는다.
	// bidirectional 형태로 정의해서 edge 가 시작 시 구독 심볼/필터를 지정 가능.
	// 1차 prototype: edge 는 빈 SubscribeRequest 만 보내고 모든 tick 수신.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[0], PriceService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Tick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeClient = grpc.ServerStreamingClient[Tick]

// PriceServiceServer is the server API for PriceService service.
// All implementations must embed UnimplementedPriceServiceServer
// for forward compatibility.
//
// PriceService 는 mci-price (Internal) 가 노출하는 gRPC 서비스다.
type PriceServiceServer interface {
	// Subscribe 는 edge 가 호출해서 Internal 로부터 tick stream 을 받는다.
	// bidirectional 형태로 정의해서 edge 가 시작 시 구독 심볼/필터를 지정 가능.
	// 1차 prototype: edge 는 빈 SubscribeRequest 만 보내고 모든 tick 수신.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Tick]) error
	mustEmbedUnimplementedPriceServiceServer()
}

// UnimplementedPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceServiceServer struct{}

func (UnimplementedPriceServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Tick]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPriceServiceServer) mustEmbedUnimplementedPriceServiceServer() {}
func (UnimplementedPriceServiceServer) testEmbeddedByValue()                      {}

// UnsafePriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServer()
}

func RegisterPriceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServer) {
	// If the following call panics, it indicates UnimplementedPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceService_ServiceDesc, srv)
}

func _PriceService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Tick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeServer = grpc.ServerStreamingServer[Tick]

// PriceService_ServiceDesc is the grpc.ServiceDesc for PriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wtg.v1.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PriceService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wtg/v1/price.proto",
}
