// WTG (Winway Trading Gateway) — Price stream service.
//
// Internal mci-price ↔ DMZ mci-edge-price 사이의 gRPC bidirectional stream.
// 시세 fan-out 의 핵심 통신 채널.
//
// 보안: mTLS gRPC (Phase 8 운영화 시점). DMZ → Internal 정방향만 정책상
// 허용되므로, edge 가 Internal 로 connect 하고 Internal 이 그 stream 으로
// tick 을 push 하는 reverse stream 패턴.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wtg/v1/price.proto

package wtgpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishAck — PublishTick stream 의 주기 응답. server 가 받은 tick 수와
// 마지막 처리 시각을 알려 publisher 가 backpressure / 끊김 진단에 활용.
type PublishAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 본 stream 에서 server 가 누적 처리한 tick 수.
	Accepted uint64 `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// 본 stream 에서 server 가 drop 한 tick 수 (backpressure / 검증 실패 등).
	Dropped uint64 `protobuf:"varint,2,opt,name=dropped,proto3" json:"dropped,omitempty"`
	// 마지막 ack 시점의 server unix nano.
	ServerUnixNano int64 `protobuf:"varint,3,opt,name=server_unix_nano,json=serverUnixNano,proto3" json:"server_unix_nano,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PublishAck) Reset() {
	*x = PublishAck{}
	mi := &file_wtg_v1_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishAck) ProtoMessage() {}

func (x *PublishAck) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishAck.ProtoReflect.Descriptor instead.
func (*PublishAck) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{0}
}

func (x *PublishAck) GetAccepted() uint64 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *PublishAck) GetDropped() uint64 {
	if x != nil {
		return x.Dropped
	}
	return 0
}

func (x *PublishAck) GetServerUnixNano() int64 {
	if x != nil {
		return x.ServerUnixNano
	}
	return 0
}

// SubscribeRequest 는 edge 가 보내는 구독 옵션 (1차는 빈 메시지).
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 구독 대상 통화쌍 화이트리스트. 비어있으면 모든 심볼 수신.
	Symbols []string `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	// 구독자 식별 (edge instance 이름 등 — 디버깅/감사용).
	SubscriberId  string `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_wtg_v1_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *SubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

// Tick 은 정규화된 시세 단위.
//
// internal/price/decoder.go 의 Tick 구조와 1:1 대응. wire 호환성은
// proto 가 단일 출처이며 Go 측 struct 는 변환 코드로 매핑.
type Tick struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	MarketId uint64                 `protobuf:"varint,1,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`
	Symbol   string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	SeqNum   uint32                 `protobuf:"varint,3,opt,name=seq_num,json=seqNum,proto3" json:"seq_num,omitempty"`
	Mask     uint32                 `protobuf:"varint,4,opt,name=mask,proto3" json:"mask,omitempty"`
	Type     uint32                 `protobuf:"varint,5,opt,name=type,proto3" json:"type,omitempty"` // pushmsg.type (uint8 → uint32 wrap)
	Flag     uint32                 `protobuf:"varint,6,opt,name=flag,proto3" json:"flag,omitempty"` // pushmsg.flag (uint8 → uint32 wrap)
	// body 는 cooker 의 시세 페이로드 raw bytes.
	// edge 는 그대로 ws 클라이언트로 forward — 해석하지 않음 (passthrough 원칙).
	Body []byte `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	// mci-price 가 디코딩한 wallclock (Unix nano). 디버깅/지연 측정용.
	ReceivedUnixNano int64 `protobuf:"varint,8,opt,name=received_unix_nano,json=receivedUnixNano,proto3" json:"received_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Tick) Reset() {
	*x = Tick{}
	mi := &file_wtg_v1_price_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tick) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tick) ProtoMessage() {}

func (x *Tick) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tick.ProtoReflect.Descriptor instead.
func (*Tick) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{2}
}

func (x *Tick) GetMarketId() uint64 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *Tick) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Tick) GetSeqNum() uint32 {
	if x != nil {
		return x.SeqNum
	}
	return 0
}

func (x *Tick) GetMask() uint32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

func (x *Tick) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Tick) GetFlag() uint32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *Tick) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Tick) GetReceivedUnixNano() int64 {
	if x != nil {
		return x.ReceivedUnixNano
	}
	return 0
}

// QuoteSubscribeRequest 는 edge 가 CustomerQuote stream 을 구독할 때 보내는 옵션.
type QuoteSubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// edge instance 식별 (디버깅/감사용).
	SubscriberId string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// 수신할 Profile 화이트리스트 (예: "WEB.BRANCH.VIP").
	// 비어있으면 모든 Profile 수신 — edge 가 사용자별 분기 책임.
	ProfileKeys []string `protobuf:"bytes,2,rep,name=profile_keys,json=profileKeys,proto3" json:"profile_keys,omitempty"`
	// 수신할 통화쌍 화이트리스트. 비어있으면 모든 pair.
	Pairs         []string `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QuoteSubscribeRequest) Reset() {
	*x = QuoteSubscribeRequest{}
	mi := &file_wtg_v1_price_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteSubscribeRequest) ProtoMessage() {}

func (x *QuoteSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteSubscribeRequest.ProtoReflect.Descriptor instead.
func (*QuoteSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{3}
}

func (x *QuoteSubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *QuoteSubscribeRequest) GetProfileKeys() []string {
	if x != nil {
		return x.ProfileKeys
	}
	return nil
}

func (x *QuoteSubscribeRequest) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// BarSubscribeRequest 는 mci-chart 가 봉 stream 을 구독할 때 보내는 옵션.
type BarSubscribeRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// 수신할 timeframe 화이트리스트 (예: "1m", "5m"). 비면 모두.
	Timeframes []string `protobuf:"bytes,2,rep,name=timeframes,proto3" json:"timeframes,omitempty"`
	// 수신할 통화쌍 화이트리스트. 비면 모두.
	Pairs         []string `protobuf:"bytes,3,rep,name=pairs,proto3" json:"pairs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BarSubscribeRequest) Reset() {
	*x = BarSubscribeRequest{}
	mi := &file_wtg_v1_price_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BarSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BarSubscribeRequest) ProtoMessage() {}

func (x *BarSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BarSubscribeRequest.ProtoReflect.Descriptor instead.
func (*BarSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{4}
}

func (x *BarSubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *BarSubscribeRequest) GetTimeframes() []string {
	if x != nil {
		return x.Timeframes
	}
	return nil
}

func (x *BarSubscribeRequest) GetPairs() []string {
	if x != nil {
		return x.Pairs
	}
	return nil
}

// Bar 는 closed 된 OHLC 봉. quote.Bar 와 1:1 대응.
type Bar struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pair           string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Tf             string                 `protobuf:"bytes,2,opt,name=tf,proto3" json:"tf,omitempty"` // "1m" / "5m" / ...
	OpenedUnixNano int64                  `protobuf:"varint,3,opt,name=opened_unix_nano,json=openedUnixNano,proto3" json:"opened_unix_nano,omitempty"`
	ClosedUnixNano int64                  `protobuf:"varint,4,opt,name=closed_unix_nano,json=closedUnixNano,proto3" json:"closed_unix_nano,omitempty"`
	OpenBid        float64                `protobuf:"fixed64,5,opt,name=open_bid,json=openBid,proto3" json:"open_bid,omitempty"`
	OpenAsk        float64                `protobuf:"fixed64,6,opt,name=open_ask,json=openAsk,proto3" json:"open_ask,omitempty"`
	HighBid        float64                `protobuf:"fixed64,7,opt,name=high_bid,json=highBid,proto3" json:"high_bid,omitempty"`
	HighAsk        float64                `protobuf:"fixed64,8,opt,name=high_ask,json=highAsk,proto3" json:"high_ask,omitempty"`
	LowBid         float64                `protobuf:"fixed64,9,opt,name=low_bid,json=lowBid,proto3" json:"low_bid,omitempty"`
	LowAsk         float64                `protobuf:"fixed64,10,opt,name=low_ask,json=lowAsk,proto3" json:"low_ask,omitempty"`
	CloseBid       float64                `protobuf:"fixed64,11,opt,name=close_bid,json=closeBid,proto3" json:"close_bid,omitempty"`
	CloseAsk       float64                `protobuf:"fixed64,12,opt,name=close_ask,json=closeAsk,proto3" json:"close_ask,omitempty"`
	TickCount      int32                  `protobuf:"varint,13,opt,name=tick_count,json=tickCount,proto3" json:"tick_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Bar) Reset() {
	*x = Bar{}
	mi := &file_wtg_v1_price_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bar) ProtoMessage() {}

func (x *Bar) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bar.ProtoReflect.Descriptor instead.
func (*Bar) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{5}
}

func (x *Bar) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *Bar) GetTf() string {
	if x != nil {
		return x.Tf
	}
	return ""
}

func (x *Bar) GetOpenedUnixNano() int64 {
	if x != nil {
		return x.OpenedUnixNano
	}
	return 0
}

func (x *Bar) GetClosedUnixNano() int64 {
	if x != nil {
		return x.ClosedUnixNano
	}
	return 0
}

func (x *Bar) GetOpenBid() float64 {
	if x != nil {
		return x.OpenBid
	}
	return 0
}

func (x *Bar) GetOpenAsk() float64 {
	if x != nil {
		return x.OpenAsk
	}
	return 0
}

func (x *Bar) GetHighBid() float64 {
	if x != nil {
		return x.HighBid
	}
	return 0
}

func (x *Bar) GetHighAsk() float64 {
	if x != nil {
		return x.HighAsk
	}
	return 0
}

func (x *Bar) GetLowBid() float64 {
	if x != nil {
		return x.LowBid
	}
	return 0
}

func (x *Bar) GetLowAsk() float64 {
	if x != nil {
		return x.LowAsk
	}
	return 0
}

func (x *Bar) GetCloseBid() float64 {
	if x != nil {
		return x.CloseBid
	}
	return 0
}

func (x *Bar) GetCloseAsk() float64 {
	if x != nil {
		return x.CloseAsk
	}
	return 0
}

func (x *Bar) GetTickCount() int32 {
	if x != nil {
		return x.TickCount
	}
	return 0
}

// CustomerQuote 는 마진 적용된 고객 노출 시세.
// pkg/pricing.CustomerQuote 와 1:1 대응. profile 정보는 edge fan-out 분기에 사용.
type CustomerQuote struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Pair    string                 `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Channel string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"` // session.Channel ("WEB"/"MOB"/"CS"/"FIX"/"ADM")
	Site    string                 `protobuf:"bytes,3,opt,name=site,proto3" json:"site,omitempty"`       // session.Site ("BRANCH"/"HQ")
	Tier    string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`       // session.Tier ("VIP"/"GOLD"/"STD"...)
	Tenor   string                 `protobuf:"bytes,5,opt,name=tenor,proto3" json:"tenor,omitempty"`     // "SPOT" / "1W" / "1M" ...
	Bid     float64                `protobuf:"fixed64,6,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask     float64                `protobuf:"fixed64,7,opt,name=ask,proto3" json:"ask,omitempty"`
	// 시세 wallclock (Unix nano). raw 시점 timestamp 유지.
	TsUnixNano int64 `protobuf:"varint,8,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	// 감사·재현용 — 산출 근거가 된 raw 값과 적용된 PricingTable.Version.
	RawBid       float64 `protobuf:"fixed64,9,opt,name=raw_bid,json=rawBid,proto3" json:"raw_bid,omitempty"`
	RawAsk       float64 `protobuf:"fixed64,10,opt,name=raw_ask,json=rawAsk,proto3" json:"raw_ask,omitempty"`
	TableVersion int64   `protobuf:"varint,11,opt,name=table_version,json=tableVersion,proto3" json:"table_version,omitempty"`
	// QuoteID — FIX 4.4 tag 117 호환 식별자. mci-price 발행, 매칭 엔진이
	// pkg/quoteid.Registry 로 검증 시 사용한다. 빈값이면 quoteid 비활성.
	QuoteId string `protobuf:"bytes,12,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	// ValidUntil — 토큰 만료 wallclock (Unix nano). 이 시점 이후 엔진은
	// 토큰을 거절해야 한다 (FX Global Code Principle 17 — last-look 한계).
	ValidUntilUnixNano int64 `protobuf:"varint,13,opt,name=valid_until_unix_nano,json=validUntilUnixNano,proto3" json:"valid_until_unix_nano,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CustomerQuote) Reset() {
	*x = CustomerQuote{}
	mi := &file_wtg_v1_price_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CustomerQuote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerQuote) ProtoMessage() {}

func (x *CustomerQuote) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_price_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerQuote.ProtoReflect.Descriptor instead.
func (*CustomerQuote) Descriptor() ([]byte, []int) {
	return file_wtg_v1_price_proto_rawDescGZIP(), []int{6}
}

func (x *CustomerQuote) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *CustomerQuote) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *CustomerQuote) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *CustomerQuote) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *CustomerQuote) GetTenor() string {
	if x != nil {
		return x.Tenor
	}
	return ""
}

func (x *CustomerQuote) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *CustomerQuote) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *CustomerQuote) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

func (x *CustomerQuote) GetRawBid() float64 {
	if x != nil {
		return x.RawBid
	}
	return 0
}

func (x *CustomerQuote) GetRawAsk() float64 {
	if x != nil {
		return x.RawAsk
	}
	return 0
}

func (x *CustomerQuote) GetTableVersion() int64 {
	if x != nil {
		return x.TableVersion
	}
	return 0
}

func (x *CustomerQuote) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *CustomerQuote) GetValidUntilUnixNano() int64 {
	if x != nil {
		return x.ValidUntilUnixNano
	}
	return 0
}

var File_wtg_v1_price_proto protoreflect.FileDescriptor

const file_wtg_v1_price_proto_rawDesc = "" +
	"\n" +
	"\x12wtg/v1/price.proto\x12\x06wtg.v1\"l\n" +
	"\n" +
	"PublishAck\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x04R\baccepted\x12\x18\n" +
	"\adropped\x18\x02 \x01(\x04R\adropped\x12(\n" +
	"\x10server_unix_nano\x18\x03 \x01(\x03R\x0eserverUnixNano\"Q\n" +
	"\x10SubscribeRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\"\xd2\x01\n" +
	"\x04Tick\x12\x1b\n" +
	"\tmarket_id\x18\x01 \x01(\x04R\bmarketId\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x17\n" +
	"\aseq_num\x18\x03 \x01(\rR\x06seqNum\x12\x12\n" +
	"\x04mask\x18\x04 \x01(\rR\x04mask\x12\x12\n" +
	"\x04type\x18\x05 \x01(\rR\x04type\x12\x12\n" +
	"\x04flag\x18\x06 \x01(\rR\x04flag\x12\x12\n" +
	"\x04body\x18\a \x01(\fR\x04body\x12,\n" +
	"\x12received_unix_nano\x18\b \x01(\x03R\x10receivedUnixNano\"u\n" +
	"\x15QuoteSubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12!\n" +
	"\fprofile_keys\x18\x02 \x03(\tR\vprofileKeys\x12\x14\n" +
	"\x05pairs\x18\x03 \x03(\tR\x05pairs\"p\n" +
	"\x13BarSubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x1e\n" +
	"\n" +
	"timeframes\x18\x02 \x03(\tR\n" +
	"timeframes\x12\x14\n" +
	"\x05pairs\x18\x03 \x03(\tR\x05pairs\"\xf4\x02\n" +
	"\x03Bar\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x0e\n" +
	"\x02tf\x18\x02 \x01(\tR\x02tf\x12(\n" +
	"\x10opened_unix_nano\x18\x03 \x01(\x03R\x0eopenedUnixNano\x12(\n" +
	"\x10closed_unix_nano\x18\x04 \x01(\x03R\x0eclosedUnixNano\x12\x19\n" +
	"\bopen_bid\x18\x05 \x01(\x01R\aopenBid\x12\x19\n" +
	"\bopen_ask\x18\x06 \x01(\x01R\aopenAsk\x12\x19\n" +
	"\bhigh_bid\x18\a \x01(\x01R\ahighBid\x12\x19\n" +
	"\bhigh_ask\x18\b \x01(\x01R\ahighAsk\x12\x17\n" +
	"\alow_bid\x18\t \x01(\x01R\x06lowBid\x12\x17\n" +
	"\alow_ask\x18\n" +
	" \x01(\x01R\x06lowAsk\x12\x1b\n" +
	"\tclose_bid\x18\v \x01(\x01R\bcloseBid\x12\x1b\n" +
	"\tclose_ask\x18\f \x01(\x01R\bcloseAsk\x12\x1d\n" +
	"\n" +
	"tick_count\x18\r \x01(\x05R\ttickCount\"\xe6\x02\n" +
	"\rCustomerQuote\x12\x12\n" +
	"\x04pair\x18\x01 \x01(\tR\x04pair\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x12\n" +
	"\x04site\x18\x03 \x01(\tR\x04site\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x14\n" +
	"\x05tenor\x18\x05 \x01(\tR\x05tenor\x12\x10\n" +
	"\x03bid\x18\x06 \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\a \x01(\x01R\x03ask\x12 \n" +
	"\fts_unix_nano\x18\b \x01(\x03R\n" +
	"tsUnixNano\x12\x17\n" +
	"\araw_bid\x18\t \x01(\x01R\x06rawBid\x12\x17\n" +
	"\araw_ask\x18\n" +
	" \x01(\x01R\x06rawAsk\x12#\n" +
	"\rtable_version\x18\v \x01(\x03R\ftableVersion\x12\x19\n" +
	"\bquote_id\x18\f \x01(\tR\aquoteId\x121\n" +
	"\x15valid_until_unix_nano\x18\r \x01(\x03R\x12validUntilUnixNano2\x80\x02\n" +
	"\fPriceService\x125\n" +
	"\tSubscribe\x12\x18.wtg.v1.SubscribeRequest\x1a\f.wtg.v1.Tick0\x01\x12H\n" +
	"\x0eSubscribeQuote\x12\x1d.wtg.v1.QuoteSubscribeRequest\x1a\x15.wtg.v1.CustomerQuote0\x01\x12:\n" +
	"\fSubscribeBar\x12\x1b.wtg.v1.BarSubscribeRequest\x1a\v.wtg.v1.Bar0\x01\x123\n" +
	"\vPublishTick\x12\f.wtg.v1.Tick\x1a\x12.wtg.v1.PublishAck(\x010\x01B3Z1github.com/winwaysystems/wtg/pkg/wtgpb/v1;wtgpbv1b\x06proto3"

var (
	file_wtg_v1_price_proto_rawDescOnce sync.Once
	file_wtg_v1_price_proto_rawDescData []byte
)

func file_wtg_v1_price_proto_rawDescGZIP() []byte {
	file_wtg_v1_price_proto_rawDescOnce.Do(func() {
		file_wtg_v1_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wtg_v1_price_proto_rawDesc), len(file_wtg_v1_price_proto_rawDesc)))
	})
	return file_wtg_v1_price_proto_rawDescData
}

var file_wtg_v1_price_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_wtg_v1_price_proto_goTypes = []any{
	(*PublishAck)(nil),            // 0: wtg.v1.PublishAck
	(*SubscribeRequest)(nil),      // 1: wtg.v1.SubscribeRequest
	(*Tick)(nil),                  // 2: wtg.v1.Tick
	(*QuoteSubscribeRequest)(nil), // 3: wtg.v1.QuoteSubscribeRequest
	(*BarSubscribeRequest)(nil),   // 4: wtg.v1.BarSubscribeRequest
	(*Bar)(nil),                   // 5: wtg.v1.Bar
	(*CustomerQuote)(nil),         // 6: wtg.v1.CustomerQuote
}
var file_wtg_v1_price_proto_depIdxs = []int32{
	1, // 0: wtg.v1.PriceService.Subscribe:input_type -> wtg.v1.SubscribeRequest
	3, // 1: wtg.v1.PriceService.SubscribeQuote:input_type -> wtg.v1.QuoteSubscribeRequest
	4, // 2: wtg.v1.PriceService.SubscribeBar:input_type -> wtg.v1.BarSubscribeRequest
	2, // 3: wtg.v1.PriceService.PublishTick:input_type -> wtg.v1.Tick
	2, // 4: wtg.v1.PriceService.Subscribe:output_type -> wtg.v1.Tick
	6, // 5: wtg.v1.PriceService.SubscribeQuote:output_type -> wtg.v1.CustomerQuote
	5, // 6: wtg.v1.PriceService.SubscribeBar:output_type -> wtg.v1.Bar
	0, // 7: wtg.v1.PriceService.PublishTick:output_type -> wtg.v1.PublishAck
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wtg_v1_price_proto_init() }
func file_wtg_v1_price_proto_init() {
	if File_wtg_v1_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wtg_v1_price_proto_rawDesc), len(file_wtg_v1_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wtg_v1_price_proto_goTypes,
		DependencyIndexes: file_wtg_v1_price_proto_depIdxs,
		MessageInfos:      file_wtg_v1_price_proto_msgTypes,
	}.Build()
	File_wtg_v1_price_proto = out.File
	file_wtg_v1_price_proto_goTypes = nil
	file_wtg_v1_price_proto_depIdxs = nil
}
