// WTG (Winway Trading Gateway) — Price stream service.
//
// Internal mci-price ↔ DMZ mci-edge-price 사이의 gRPC bidirectional stream.
// 시세 fan-out 의 핵심 통신 채널.
//
// 보안: mTLS gRPC (Phase 8 운영화 시점). DMZ → Internal 정방향만 정책상
// 허용되므로, edge 가 Internal 로 connect 하고 Internal 이 그 stream 으로
// tick 을 push 하는 reverse stream 패턴.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: wtg/v1/price.proto

package wtgpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PriceService_Subscribe_FullMethodName              = "/wtg.v1.PriceService/Subscribe"
	PriceService_SubscribeQuote_FullMethodName         = "/wtg.v1.PriceService/SubscribeQuote"
	PriceService_SubscribeBar_FullMethodName           = "/wtg.v1.PriceService/SubscribeBar"
	PriceService_RegisterCustomer_FullMethodName       = "/wtg.v1.PriceService/RegisterCustomer"
	PriceService_SubscribeCustomerQuote_FullMethodName = "/wtg.v1.PriceService/SubscribeCustomerQuote"
	PriceService_PublishTick_FullMethodName            = "/wtg.v1.PriceService/PublishTick"
)

// PriceServiceClient is the client API for PriceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PriceService 는 mci-price (Internal) 가 노출하는 gRPC 서비스다.
type PriceServiceClient interface {
	// Subscribe 는 edge 가 호출해서 Internal 로부터 raw tick stream 을 받는다.
	// 마진 적용 전 시세 — 디버깅 / 모니터링 / 전체 broadcast 용.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error)
	// SubscribeQuote 는 edge 가 호출해서 Internal 로부터 마진 적용된 Profile 별
	// CustomerQuote stream 을 받는다. mci-price 의 PricingConsumer 가 publish 하는
	// 동일 데이터를 broker 외에 이 stream 으로도 push (이중 publish).
	SubscribeQuote(ctx context.Context, in *QuoteSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CustomerQuote], error)
	// SubscribeBar 는 mci-chart 가 호출해서 봉 close 이벤트 stream 을 받는다.
	// Aggregator 가 closed 한 봉이 Archiver(DB) 와 병렬로 이 stream 으로도 push.
	// 클라이언트(mci-chart)는 (pair, tf) 필터를 옵션으로 지정.
	SubscribeBar(ctx context.Context, in *BarSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bar], error)
	// RegisterCustomer — Phase 4b. edge-price 가 ws 클라이언트별로 customer
	// 등록/해제 이벤트를 bidirectional stream 으로 보낸다. stream 종료 시 본
	// stream 으로 등록한 모든 customer 자동 해제 — edge 재시작 / 끊김 시 stale
	// 등록 방지.
	//
	// 흐름:
	//
	//	edge ─ CustomerRegistration{op=REGISTER,customer_id,profile_key} ─→ server
	//	server ─ CustomerAck{ok=true} ─→ edge
	//	...
	//	edge ─ CustomerRegistration{op=UNREGISTER,customer_id} ─→ server
	//	... (stream 유지 — ws 클라이언트 여러 개)
	//	edge disconnect → server 가 등록 set 전체 unregister
	RegisterCustomer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CustomerRegistration, CustomerAck], error)
	// SubscribeCustomerQuote — Phase 4b. customer-tag 된 quote stream.
	// PricingConsumer 의 customer fan-out 결과를 받는다. Profile-only quote
	// (SubscribeQuote) 와 분리 — customer_id 기반 필터링 단순화.
	SubscribeCustomerQuote(ctx context.Context, in *CustomerQuoteSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CustomerQuote], error)
	// PublishTick 은 quote-forwarder 가 호출해서 mci-price 에 시세를 직접 push 하는
	// 양방향 stream. broker 의 PRICE exchange fan-out 을 우회 — broker 가 매매
	// transaction 에만 집중하도록 시세 부하를 분리한다.
	//
	// 흐름:
	//
	//	forwarder (gRPC client) ─→ stream Tick ─→ mci-price (gRPC server)
	//	                                             │
	//	                                             └─→ BestConsumer / Aggregator / PricingConsumer
	//
	// ack: 주기적 (batch) 으로 server 가 publisher 에 ack 회신 — backpressure / 통계용.
	PublishTick(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Tick, PublishAck], error)
}

type priceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPriceServiceClient(cc grpc.ClientConnInterface) PriceServiceClient {
	return &priceServiceClient{cc}
}

func (c *priceServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Tick], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[0], PriceService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, Tick]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeClient = grpc.ServerStreamingClient[Tick]

func (c *priceServiceClient) SubscribeQuote(ctx context.Context, in *QuoteSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CustomerQuote], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[1], PriceService_SubscribeQuote_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QuoteSubscribeRequest, CustomerQuote]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeQuoteClient = grpc.ServerStreamingClient[CustomerQuote]

func (c *priceServiceClient) SubscribeBar(ctx context.Context, in *BarSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Bar], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[2], PriceService_SubscribeBar_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BarSubscribeRequest, Bar]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeBarClient = grpc.ServerStreamingClient[Bar]

func (c *priceServiceClient) RegisterCustomer(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CustomerRegistration, CustomerAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[3], PriceService_RegisterCustomer_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CustomerRegistration, CustomerAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_RegisterCustomerClient = grpc.BidiStreamingClient[CustomerRegistration, CustomerAck]

func (c *priceServiceClient) SubscribeCustomerQuote(ctx context.Context, in *CustomerQuoteSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[CustomerQuote], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[4], PriceService_SubscribeCustomerQuote_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CustomerQuoteSubscribeRequest, CustomerQuote]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeCustomerQuoteClient = grpc.ServerStreamingClient[CustomerQuote]

func (c *priceServiceClient) PublishTick(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Tick, PublishAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PriceService_ServiceDesc.Streams[5], PriceService_PublishTick_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Tick, PublishAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_PublishTickClient = grpc.BidiStreamingClient[Tick, PublishAck]

// PriceServiceServer is the server API for PriceService service.
// All implementations must embed UnimplementedPriceServiceServer
// for forward compatibility.
//
// PriceService 는 mci-price (Internal) 가 노출하는 gRPC 서비스다.
type PriceServiceServer interface {
	// Subscribe 는 edge 가 호출해서 Internal 로부터 raw tick stream 을 받는다.
	// 마진 적용 전 시세 — 디버깅 / 모니터링 / 전체 broadcast 용.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Tick]) error
	// SubscribeQuote 는 edge 가 호출해서 Internal 로부터 마진 적용된 Profile 별
	// CustomerQuote stream 을 받는다. mci-price 의 PricingConsumer 가 publish 하는
	// 동일 데이터를 broker 외에 이 stream 으로도 push (이중 publish).
	SubscribeQuote(*QuoteSubscribeRequest, grpc.ServerStreamingServer[CustomerQuote]) error
	// SubscribeBar 는 mci-chart 가 호출해서 봉 close 이벤트 stream 을 받는다.
	// Aggregator 가 closed 한 봉이 Archiver(DB) 와 병렬로 이 stream 으로도 push.
	// 클라이언트(mci-chart)는 (pair, tf) 필터를 옵션으로 지정.
	SubscribeBar(*BarSubscribeRequest, grpc.ServerStreamingServer[Bar]) error
	// RegisterCustomer — Phase 4b. edge-price 가 ws 클라이언트별로 customer
	// 등록/해제 이벤트를 bidirectional stream 으로 보낸다. stream 종료 시 본
	// stream 으로 등록한 모든 customer 자동 해제 — edge 재시작 / 끊김 시 stale
	// 등록 방지.
	//
	// 흐름:
	//
	//	edge ─ CustomerRegistration{op=REGISTER,customer_id,profile_key} ─→ server
	//	server ─ CustomerAck{ok=true} ─→ edge
	//	...
	//	edge ─ CustomerRegistration{op=UNREGISTER,customer_id} ─→ server
	//	... (stream 유지 — ws 클라이언트 여러 개)
	//	edge disconnect → server 가 등록 set 전체 unregister
	RegisterCustomer(grpc.BidiStreamingServer[CustomerRegistration, CustomerAck]) error
	// SubscribeCustomerQuote — Phase 4b. customer-tag 된 quote stream.
	// PricingConsumer 의 customer fan-out 결과를 받는다. Profile-only quote
	// (SubscribeQuote) 와 분리 — customer_id 기반 필터링 단순화.
	SubscribeCustomerQuote(*CustomerQuoteSubscribeRequest, grpc.ServerStreamingServer[CustomerQuote]) error
	// PublishTick 은 quote-forwarder 가 호출해서 mci-price 에 시세를 직접 push 하는
	// 양방향 stream. broker 의 PRICE exchange fan-out 을 우회 — broker 가 매매
	// transaction 에만 집중하도록 시세 부하를 분리한다.
	//
	// 흐름:
	//
	//	forwarder (gRPC client) ─→ stream Tick ─→ mci-price (gRPC server)
	//	                                             │
	//	                                             └─→ BestConsumer / Aggregator / PricingConsumer
	//
	// ack: 주기적 (batch) 으로 server 가 publisher 에 ack 회신 — backpressure / 통계용.
	PublishTick(grpc.BidiStreamingServer[Tick, PublishAck]) error
	mustEmbedUnimplementedPriceServiceServer()
}

// UnimplementedPriceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPriceServiceServer struct{}

func (UnimplementedPriceServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[Tick]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPriceServiceServer) SubscribeQuote(*QuoteSubscribeRequest, grpc.ServerStreamingServer[CustomerQuote]) error {
	return status.Error(codes.Unimplemented, "method SubscribeQuote not implemented")
}
func (UnimplementedPriceServiceServer) SubscribeBar(*BarSubscribeRequest, grpc.ServerStreamingServer[Bar]) error {
	return status.Error(codes.Unimplemented, "method SubscribeBar not implemented")
}
func (UnimplementedPriceServiceServer) RegisterCustomer(grpc.BidiStreamingServer[CustomerRegistration, CustomerAck]) error {
	return status.Error(codes.Unimplemented, "method RegisterCustomer not implemented")
}
func (UnimplementedPriceServiceServer) SubscribeCustomerQuote(*CustomerQuoteSubscribeRequest, grpc.ServerStreamingServer[CustomerQuote]) error {
	return status.Error(codes.Unimplemented, "method SubscribeCustomerQuote not implemented")
}
func (UnimplementedPriceServiceServer) PublishTick(grpc.BidiStreamingServer[Tick, PublishAck]) error {
	return status.Error(codes.Unimplemented, "method PublishTick not implemented")
}
func (UnimplementedPriceServiceServer) mustEmbedUnimplementedPriceServiceServer() {}
func (UnimplementedPriceServiceServer) testEmbeddedByValue()                      {}

// UnsafePriceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PriceServiceServer will
// result in compilation errors.
type UnsafePriceServiceServer interface {
	mustEmbedUnimplementedPriceServiceServer()
}

func RegisterPriceServiceServer(s grpc.ServiceRegistrar, srv PriceServiceServer) {
	// If the following call panics, it indicates UnimplementedPriceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PriceService_ServiceDesc, srv)
}

func _PriceService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, Tick]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeServer = grpc.ServerStreamingServer[Tick]

func _PriceService_SubscribeQuote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QuoteSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).SubscribeQuote(m, &grpc.GenericServerStream[QuoteSubscribeRequest, CustomerQuote]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeQuoteServer = grpc.ServerStreamingServer[CustomerQuote]

func _PriceService_SubscribeBar_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BarSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).SubscribeBar(m, &grpc.GenericServerStream[BarSubscribeRequest, Bar]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeBarServer = grpc.ServerStreamingServer[Bar]

func _PriceService_RegisterCustomer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PriceServiceServer).RegisterCustomer(&grpc.GenericServerStream[CustomerRegistration, CustomerAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_RegisterCustomerServer = grpc.BidiStreamingServer[CustomerRegistration, CustomerAck]

func _PriceService_SubscribeCustomerQuote_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CustomerQuoteSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PriceServiceServer).SubscribeCustomerQuote(m, &grpc.GenericServerStream[CustomerQuoteSubscribeRequest, CustomerQuote]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_SubscribeCustomerQuoteServer = grpc.ServerStreamingServer[CustomerQuote]

func _PriceService_PublishTick_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PriceServiceServer).PublishTick(&grpc.GenericServerStream[Tick, PublishAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PriceService_PublishTickServer = grpc.BidiStreamingServer[Tick, PublishAck]

// PriceService_ServiceDesc is the grpc.ServiceDesc for PriceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PriceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wtg.v1.PriceService",
	HandlerType: (*PriceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PriceService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeQuote",
			Handler:       _PriceService_SubscribeQuote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeBar",
			Handler:       _PriceService_SubscribeBar_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RegisterCustomer",
			Handler:       _PriceService_RegisterCustomer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "SubscribeCustomerQuote",
			Handler:       _PriceService_SubscribeCustomerQuote_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PublishTick",
			Handler:       _PriceService_PublishTick_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "wtg/v1/price.proto",
}
