// WTG (Winway Trading Gateway) — Push fan-out service.
//
// Internal mci-push ↔ DMZ mci-edge-push 사이의 gRPC stream.
// 매매 엔진의 unsolicited 메시지(체결, 주문상태, 알림)를 사용자 단말까지
// 전달하는 역방향(reverse) 흐름.
//
// 1차 prototype 의 단순화:
//   - edge 는 빈 SubscribeRequest 만 보냄.
//   - mci-push 는 모든 unsolicited 를 stream 으로 forward.
//   - logon_id 기반 사용자 매핑은 edge 가 자체 Registry 로 처리.
//   - 2차에서는 edge 가 자기 가진 logon_id 화이트리스트를 보내서 broker→edge
//     트래픽 효율화 가능 (운영 측정 후 결정).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: wtg/v1/push.proto

package wtgpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PushService_Subscribe_FullMethodName = "/wtg.v1.PushService/Subscribe"
)

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PushService 는 mci-push (Internal) 가 노출하는 gRPC 서비스.
type PushServiceClient interface {
	// Subscribe 는 edge 가 호출해서 Internal 로부터 push 메시지 stream 을 받는다.
	Subscribe(ctx context.Context, in *PushSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PushMessage], error)
}

type pushServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPushServiceClient(cc grpc.ClientConnInterface) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) Subscribe(ctx context.Context, in *PushSubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PushMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PushService_ServiceDesc.Streams[0], PushService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PushSubscribeRequest, PushMessage]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushService_SubscribeClient = grpc.ServerStreamingClient[PushMessage]

// PushServiceServer is the server API for PushService service.
// All implementations must embed UnimplementedPushServiceServer
// for forward compatibility.
//
// PushService 는 mci-push (Internal) 가 노출하는 gRPC 서비스.
type PushServiceServer interface {
	// Subscribe 는 edge 가 호출해서 Internal 로부터 push 메시지 stream 을 받는다.
	Subscribe(*PushSubscribeRequest, grpc.ServerStreamingServer[PushMessage]) error
	mustEmbedUnimplementedPushServiceServer()
}

// UnimplementedPushServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPushServiceServer struct{}

func (UnimplementedPushServiceServer) Subscribe(*PushSubscribeRequest, grpc.ServerStreamingServer[PushMessage]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPushServiceServer) mustEmbedUnimplementedPushServiceServer() {}
func (UnimplementedPushServiceServer) testEmbeddedByValue()                     {}

// UnsafePushServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PushServiceServer will
// result in compilation errors.
type UnsafePushServiceServer interface {
	mustEmbedUnimplementedPushServiceServer()
}

func RegisterPushServiceServer(s grpc.ServiceRegistrar, srv PushServiceServer) {
	// If the following call panics, it indicates UnimplementedPushServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PushService_ServiceDesc, srv)
}

func _PushService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PushSubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PushServiceServer).Subscribe(m, &grpc.GenericServerStream[PushSubscribeRequest, PushMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PushService_SubscribeServer = grpc.ServerStreamingServer[PushMessage]

// PushService_ServiceDesc is the grpc.ServiceDesc for PushService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PushService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wtg.v1.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PushService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "wtg/v1/push.proto",
}
