// WTG (Winway Trading Gateway) — Push fan-out service.
//
// Internal mci-push ↔ DMZ mci-edge-push 사이의 gRPC stream.
// 매매 엔진의 unsolicited 메시지(체결, 주문상태, 알림)를 사용자 단말까지
// 전달하는 역방향(reverse) 흐름.
//
// 1차 prototype 의 단순화:
//   - edge 는 빈 SubscribeRequest 만 보냄.
//   - mci-push 는 모든 unsolicited 를 stream 으로 forward.
//   - logon_id 기반 사용자 매핑은 edge 가 자체 Registry 로 처리.
//   - 2차에서는 edge 가 자기 가진 logon_id 화이트리스트를 보내서 broker→edge
//     트래픽 효율화 가능 (운영 측정 후 결정).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wtg/v1/push.proto

package wtgpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PushSubscribeRequest 는 edge 가 보내는 구독 옵션.
type PushSubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 구독자(=edge 인스턴스) 식별자 — 로그/감사용.
	SubscriberId  string `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSubscribeRequest) Reset() {
	*x = PushSubscribeRequest{}
	mi := &file_wtg_v1_push_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSubscribeRequest) ProtoMessage() {}

func (x *PushSubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_push_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSubscribeRequest.ProtoReflect.Descriptor instead.
func (*PushSubscribeRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_push_proto_rawDescGZIP(), []int{0}
}

func (x *PushSubscribeRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

// PushMessage 는 매매 엔진이 발행한 단일 사용자/브로드캐스트 push.
//
// edge 는 logon_id 가 비어있지 않으면 해당 사용자의 모든 ws 에 fan-out,
// 비어있으면 broadcast (시스템 알림 등) 처리.
type PushMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mymq 함수 코드: FCCast=4, FCPush=13, FCSignal=14.
	Func uint32 `protobuf:"varint,1,opt,name=func,proto3" json:"func,omitempty"`
	Subc uint32 `protobuf:"varint,2,opt,name=subc,proto3" json:"subc,omitempty"`
	// broadcast prefix 에서 추출된 메타.
	Exchange string `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Channel  string `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	LogonId  string `protobuf:"bytes,5,opt,name=logon_id,json=logonId,proto3" json:"logon_id,omitempty"`
	// raw payload (cooker / 매매 엔진이 보낸 본문 그대로).
	// edge 는 해석하지 않고 ws 클라이언트로 forward.
	Data []byte `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	// 디버깅/지연 측정용.
	ReceivedUnixNano int64 `protobuf:"varint,7,opt,name=received_unix_nano,json=receivedUnixNano,proto3" json:"received_unix_nano,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PushMessage) Reset() {
	*x = PushMessage{}
	mi := &file_wtg_v1_push_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushMessage) ProtoMessage() {}

func (x *PushMessage) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_push_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushMessage.ProtoReflect.Descriptor instead.
func (*PushMessage) Descriptor() ([]byte, []int) {
	return file_wtg_v1_push_proto_rawDescGZIP(), []int{1}
}

func (x *PushMessage) GetFunc() uint32 {
	if x != nil {
		return x.Func
	}
	return 0
}

func (x *PushMessage) GetSubc() uint32 {
	if x != nil {
		return x.Subc
	}
	return 0
}

func (x *PushMessage) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *PushMessage) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *PushMessage) GetLogonId() string {
	if x != nil {
		return x.LogonId
	}
	return ""
}

func (x *PushMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PushMessage) GetReceivedUnixNano() int64 {
	if x != nil {
		return x.ReceivedUnixNano
	}
	return 0
}

var File_wtg_v1_push_proto protoreflect.FileDescriptor

const file_wtg_v1_push_proto_rawDesc = "" +
	"\n" +
	"\x11wtg/v1/push.proto\x12\x06wtg.v1\";\n" +
	"\x14PushSubscribeRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\"\xc8\x01\n" +
	"\vPushMessage\x12\x12\n" +
	"\x04func\x18\x01 \x01(\rR\x04func\x12\x12\n" +
	"\x04subc\x18\x02 \x01(\rR\x04subc\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12\x19\n" +
	"\blogon_id\x18\x05 \x01(\tR\alogonId\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12,\n" +
	"\x12received_unix_nano\x18\a \x01(\x03R\x10receivedUnixNano2O\n" +
	"\vPushService\x12@\n" +
	"\tSubscribe\x12\x1c.wtg.v1.PushSubscribeRequest\x1a\x13.wtg.v1.PushMessage0\x01B3Z1github.com/winwaysystems/wtg/pkg/wtgpb/v1;wtgpbv1b\x06proto3"

var (
	file_wtg_v1_push_proto_rawDescOnce sync.Once
	file_wtg_v1_push_proto_rawDescData []byte
)

func file_wtg_v1_push_proto_rawDescGZIP() []byte {
	file_wtg_v1_push_proto_rawDescOnce.Do(func() {
		file_wtg_v1_push_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wtg_v1_push_proto_rawDesc), len(file_wtg_v1_push_proto_rawDesc)))
	})
	return file_wtg_v1_push_proto_rawDescData
}

var file_wtg_v1_push_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_wtg_v1_push_proto_goTypes = []any{
	(*PushSubscribeRequest)(nil), // 0: wtg.v1.PushSubscribeRequest
	(*PushMessage)(nil),          // 1: wtg.v1.PushMessage
}
var file_wtg_v1_push_proto_depIdxs = []int32{
	0, // 0: wtg.v1.PushService.Subscribe:input_type -> wtg.v1.PushSubscribeRequest
	1, // 1: wtg.v1.PushService.Subscribe:output_type -> wtg.v1.PushMessage
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_wtg_v1_push_proto_init() }
func file_wtg_v1_push_proto_init() {
	if File_wtg_v1_push_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wtg_v1_push_proto_rawDesc), len(file_wtg_v1_push_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wtg_v1_push_proto_goTypes,
		DependencyIndexes: file_wtg_v1_push_proto_depIdxs,
		MessageInfos:      file_wtg_v1_push_proto_msgTypes,
	}.Build()
	File_wtg_v1_push_proto = out.File
	file_wtg_v1_push_proto_goTypes = nil
	file_wtg_v1_push_proto_depIdxs = nil
}
