// QuoteValidationService — 매칭 엔진이 NewOrderSingle (FIX 'D') 의 QuoteID
// (FIX 4.4 tag 117) 를 검증하기 위해 호출하는 RPC.
//
// 설계 / 정책 분담 / 호출 흐름은 docs/quoteid-validation-rfc.md 참조.
//
// 정합성:
//   FIX 4.4    — tag 117 (QuoteID), tag 62 (ValidUntilTime), tag 103 (OrdRejReason)
//   FX Global Code 2024 Principle 17 — last-look 투명성
//   MiFID II RTS 27 — best-execution audit trail

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: wtg/v1/quote_validation.proto

package wtgpbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationStatus int32

const (
	ValidationStatus_STATUS_UNSPECIFIED ValidationStatus = 0
	// 발행 기록 존재, 아직 ValidUntil 도래 X, 아직 사용 안 됨 — 거래 가능.
	ValidationStatus_OK ValidationStatus = 1
	// Registry 에 없음. 한 번도 발행 안 됐거나 ValidUntil + grace 후 GC.
	ValidationStatus_NOT_FOUND ValidationStatus = 2
	// ValidUntil 도래 후 grace 안 (기록은 있지만 거래 불가).
	ValidationStatus_EXPIRED ValidationStatus = 3
	// 이미 MarkConsumed 호출됨 — 다른 주문이 이 QuoteID 를 사용했다.
	ValidationStatus_ALREADY_CONSUMED ValidationStatus = 4
)

// Enum value maps for ValidationStatus.
var (
	ValidationStatus_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "OK",
		2: "NOT_FOUND",
		3: "EXPIRED",
		4: "ALREADY_CONSUMED",
	}
	ValidationStatus_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"OK":                 1,
		"NOT_FOUND":          2,
		"EXPIRED":            3,
		"ALREADY_CONSUMED":   4,
	}
)

func (x ValidationStatus) Enum() *ValidationStatus {
	p := new(ValidationStatus)
	*p = x
	return p
}

func (x ValidationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValidationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_wtg_v1_quote_validation_proto_enumTypes[0].Descriptor()
}

func (ValidationStatus) Type() protoreflect.EnumType {
	return &file_wtg_v1_quote_validation_proto_enumTypes[0]
}

func (x ValidationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValidationStatus.Descriptor instead.
func (ValidationStatus) EnumDescriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{0}
}

type ValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// FIX tag 117 — 클라이언트 NewOrderSingle 이 들고온 QuoteID 그대로.
	QuoteId string `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	// 엔진 식별 — audit 로깅 / 통계용. 사전 등록된 식별자 사용 권장
	// (예: "matching-engine-A"). RFC §10.3.
	EngineId string `protobuf:"bytes,10,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	// RPC 발신 wallclock (Unix nano) — clock skew 모니터링용.
	TsUnixNano    int64 `protobuf:"varint,11,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *ValidateRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *ValidateRequest) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

type ValidateResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status ValidationStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=wtg.v1.ValidationStatus" json:"status,omitempty"`
	// status == OK 일 때만 채워진다. 엔진은 record.bid / record.ask 를
	// 자체 정책 검증의 입력으로 사용.
	Record *QuoteRecord `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	// FIX OrdRejReason (tag 103). status != OK 일 때 채워짐.
	// 엔진은 ExecutionReport(8) 에 그대로 전달 가능 — 감독당국 호환.
	OrdRejReason int32 `protobuf:"varint,3,opt,name=ord_rej_reason,json=ordRejReason,proto3" json:"ord_rej_reason,omitempty"`
	// 사람용 reject 설명 (감독당국 로그 / debugging 보조).
	RejectText    string `protobuf:"bytes,4,opt,name=reject_text,json=rejectText,proto3" json:"reject_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateResponse) GetStatus() ValidationStatus {
	if x != nil {
		return x.Status
	}
	return ValidationStatus_STATUS_UNSPECIFIED
}

func (x *ValidateResponse) GetRecord() *QuoteRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ValidateResponse) GetOrdRejReason() int32 {
	if x != nil {
		return x.OrdRejReason
	}
	return 0
}

func (x *ValidateResponse) GetRejectText() string {
	if x != nil {
		return x.RejectText
	}
	return ""
}

type MarkConsumedRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	QuoteId string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	// 누가 사용했는지 — audit. 보통 OrderID 등 엔진 내부 식별자.
	ConsumerId string `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// 호출자(엔진) 식별 — Validate 와 동일.
	EngineId      string `protobuf:"bytes,10,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	TsUnixNano    int64  `protobuf:"varint,11,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkConsumedRequest) Reset() {
	*x = MarkConsumedRequest{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConsumedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConsumedRequest) ProtoMessage() {}

func (x *MarkConsumedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConsumedRequest.ProtoReflect.Descriptor instead.
func (*MarkConsumedRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{2}
}

func (x *MarkConsumedRequest) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *MarkConsumedRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *MarkConsumedRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *MarkConsumedRequest) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

type BatchValidateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 검증할 QuoteID 목록. 빈 배열이면 빈 results 반환. 1000 초과시 InvalidArgument.
	QuoteIds []string `protobuf:"bytes,1,rep,name=quote_ids,json=quoteIds,proto3" json:"quote_ids,omitempty"`
	// Validate 와 동일한 컨텍스트 필드 — batch 전체에 적용.
	EngineId      string `protobuf:"bytes,10,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	TsUnixNano    int64  `protobuf:"varint,11,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchValidateRequest) Reset() {
	*x = BatchValidateRequest{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchValidateRequest) ProtoMessage() {}

func (x *BatchValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchValidateRequest.ProtoReflect.Descriptor instead.
func (*BatchValidateRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{3}
}

func (x *BatchValidateRequest) GetQuoteIds() []string {
	if x != nil {
		return x.QuoteIds
	}
	return nil
}

func (x *BatchValidateRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *BatchValidateRequest) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

type BatchValidateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// results[i] 는 request.quote_ids[i] 의 검증 결과. 길이는 입력과 동일.
	// 개별 항목의 status 가 각 quote_id 에 대한 분기 — 일부 OK 일부 NOT_FOUND
	// 처럼 혼재 가능.
	Results       []*ValidateResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchValidateResponse) Reset() {
	*x = BatchValidateResponse{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchValidateResponse) ProtoMessage() {}

func (x *BatchValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchValidateResponse.ProtoReflect.Descriptor instead.
func (*BatchValidateResponse) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{4}
}

func (x *BatchValidateResponse) GetResults() []*ValidateResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

// ConsumeItem — BatchMarkConsumed 한 항목.
type ConsumeItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteId       string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeItem) Reset() {
	*x = ConsumeItem{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeItem) ProtoMessage() {}

func (x *ConsumeItem) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeItem.ProtoReflect.Descriptor instead.
func (*ConsumeItem) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{5}
}

func (x *ConsumeItem) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *ConsumeItem) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

type BatchMarkConsumedRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 표시할 (quote_id, consumer_id) 항목들. 빈 배열이면 빈 results 반환.
	// 1000 초과 시 InvalidArgument.
	Items         []*ConsumeItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	EngineId      string         `protobuf:"bytes,10,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	TsUnixNano    int64          `protobuf:"varint,11,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMarkConsumedRequest) Reset() {
	*x = BatchMarkConsumedRequest{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMarkConsumedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMarkConsumedRequest) ProtoMessage() {}

func (x *BatchMarkConsumedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMarkConsumedRequest.ProtoReflect.Descriptor instead.
func (*BatchMarkConsumedRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{6}
}

func (x *BatchMarkConsumedRequest) GetItems() []*ConsumeItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BatchMarkConsumedRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *BatchMarkConsumedRequest) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

type BatchMarkConsumedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// results[i] 는 request.items[i] 의 표시 결과. 길이는 입력과 동일.
	Results       []*MarkConsumedResponse `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchMarkConsumedResponse) Reset() {
	*x = BatchMarkConsumedResponse{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchMarkConsumedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchMarkConsumedResponse) ProtoMessage() {}

func (x *BatchMarkConsumedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchMarkConsumedResponse.ProtoReflect.Descriptor instead.
func (*BatchMarkConsumedResponse) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{7}
}

func (x *BatchMarkConsumedResponse) GetResults() []*MarkConsumedResponse {
	if x != nil {
		return x.Results
	}
	return nil
}

type MarkConsumedResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ConsumeResult — 원자적 결과.
	//
	//	OK               : 이 호출이 처음 표시 — 체결 진행.
	//	ALREADY_CONSUMED : 다른 호출이 먼저 표시했다 — 거절.
	//	NOT_FOUND        : record 없음 (GC 또는 한 번도 발행 안 됨).
	//	EXPIRED          : ValidUntil 도래 — 표시 시도해도 거래 불가.
	Status ValidationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=wtg.v1.ValidationStatus" json:"status,omitempty"`
	// OK / ALREADY_CONSUMED 시 채워짐. NOT_FOUND 는 비어있음.
	Record *QuoteRecord `protobuf:"bytes,2,opt,name=record,proto3" json:"record,omitempty"`
	// ALREADY_CONSUMED 시: 먼저 표시한 consumer_id (감사용).
	ConsumedBy string `protobuf:"bytes,3,opt,name=consumed_by,json=consumedBy,proto3" json:"consumed_by,omitempty"`
	// FIX OrdRejReason (tag 103) 매핑.
	OrdRejReason  int32  `protobuf:"varint,4,opt,name=ord_rej_reason,json=ordRejReason,proto3" json:"ord_rej_reason,omitempty"`
	RejectText    string `protobuf:"bytes,5,opt,name=reject_text,json=rejectText,proto3" json:"reject_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkConsumedResponse) Reset() {
	*x = MarkConsumedResponse{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkConsumedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkConsumedResponse) ProtoMessage() {}

func (x *MarkConsumedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkConsumedResponse.ProtoReflect.Descriptor instead.
func (*MarkConsumedResponse) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{8}
}

func (x *MarkConsumedResponse) GetStatus() ValidationStatus {
	if x != nil {
		return x.Status
	}
	return ValidationStatus_STATUS_UNSPECIFIED
}

func (x *MarkConsumedResponse) GetRecord() *QuoteRecord {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *MarkConsumedResponse) GetConsumedBy() string {
	if x != nil {
		return x.ConsumedBy
	}
	return ""
}

func (x *MarkConsumedResponse) GetOrdRejReason() int32 {
	if x != nil {
		return x.OrdRejReason
	}
	return 0
}

func (x *MarkConsumedResponse) GetRejectText() string {
	if x != nil {
		return x.RejectText
	}
	return ""
}

// ValidateSwapRequest — swap_id 한 개로 두 leg 동시 검증.
type ValidateSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwapId        string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	EngineId      string                 `protobuf:"bytes,10,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	TsUnixNano    int64                  `protobuf:"varint,11,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSwapRequest) Reset() {
	*x = ValidateSwapRequest{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSwapRequest) ProtoMessage() {}

func (x *ValidateSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSwapRequest.ProtoReflect.Descriptor instead.
func (*ValidateSwapRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *ValidateSwapRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *ValidateSwapRequest) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

// ValidateSwapResponse — swap 단위 결과 + 개별 leg 결과.
//
//	swap_status:
//	  OK              : 두 leg 모두 OK — 거래 가능.
//	  NOT_FOUND       : swap_id 자체 미존재 / 만료.
//	  EXPIRED         : 두 leg 중 하나라도 EXPIRED.
//	  ALREADY_CONSUMED: 두 leg 중 하나라도 ALREADY_CONSUMED.
//	near / far : 개별 leg 의 ValidateResponse (audit + reject 이유 추적).
type ValidateSwapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwapStatus    ValidationStatus       `protobuf:"varint,1,opt,name=swap_status,json=swapStatus,proto3,enum=wtg.v1.ValidationStatus" json:"swap_status,omitempty"`
	Near          *ValidateResponse      `protobuf:"bytes,2,opt,name=near,proto3" json:"near,omitempty"`
	Far           *ValidateResponse      `protobuf:"bytes,3,opt,name=far,proto3" json:"far,omitempty"`
	OrdRejReason  int32                  `protobuf:"varint,4,opt,name=ord_rej_reason,json=ordRejReason,proto3" json:"ord_rej_reason,omitempty"`
	RejectText    string                 `protobuf:"bytes,5,opt,name=reject_text,json=rejectText,proto3" json:"reject_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSwapResponse) Reset() {
	*x = ValidateSwapResponse{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSwapResponse) ProtoMessage() {}

func (x *ValidateSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSwapResponse.ProtoReflect.Descriptor instead.
func (*ValidateSwapResponse) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{10}
}

func (x *ValidateSwapResponse) GetSwapStatus() ValidationStatus {
	if x != nil {
		return x.SwapStatus
	}
	return ValidationStatus_STATUS_UNSPECIFIED
}

func (x *ValidateSwapResponse) GetNear() *ValidateResponse {
	if x != nil {
		return x.Near
	}
	return nil
}

func (x *ValidateSwapResponse) GetFar() *ValidateResponse {
	if x != nil {
		return x.Far
	}
	return nil
}

func (x *ValidateSwapResponse) GetOrdRejReason() int32 {
	if x != nil {
		return x.OrdRejReason
	}
	return 0
}

func (x *ValidateSwapResponse) GetRejectText() string {
	if x != nil {
		return x.RejectText
	}
	return ""
}

// ConsumeSwapRequest — 두 leg 동시 표시.
type ConsumeSwapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SwapId        string                 `protobuf:"bytes,1,opt,name=swap_id,json=swapId,proto3" json:"swap_id,omitempty"`
	ConsumerId    string                 `protobuf:"bytes,2,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"` // 매매 AP 의 거래 식별자 (OrderID 등)
	EngineId      string                 `protobuf:"bytes,10,opt,name=engine_id,json=engineId,proto3" json:"engine_id,omitempty"`
	TsUnixNano    int64                  `protobuf:"varint,11,opt,name=ts_unix_nano,json=tsUnixNano,proto3" json:"ts_unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeSwapRequest) Reset() {
	*x = ConsumeSwapRequest{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeSwapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeSwapRequest) ProtoMessage() {}

func (x *ConsumeSwapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeSwapRequest.ProtoReflect.Descriptor instead.
func (*ConsumeSwapRequest) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{11}
}

func (x *ConsumeSwapRequest) GetSwapId() string {
	if x != nil {
		return x.SwapId
	}
	return ""
}

func (x *ConsumeSwapRequest) GetConsumerId() string {
	if x != nil {
		return x.ConsumerId
	}
	return ""
}

func (x *ConsumeSwapRequest) GetEngineId() string {
	if x != nil {
		return x.EngineId
	}
	return ""
}

func (x *ConsumeSwapRequest) GetTsUnixNano() int64 {
	if x != nil {
		return x.TsUnixNano
	}
	return 0
}

// ConsumeSwapResponse — 두 leg 표시 결과. status=OK 일 때만 둘 다 OK 로 표시됨.
// status != OK 면 두 leg 중 하나 또는 둘 다 표시 안 됨 (atomic-skip).
type ConsumeSwapResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SwapStatus ValidationStatus       `protobuf:"varint,1,opt,name=swap_status,json=swapStatus,proto3,enum=wtg.v1.ValidationStatus" json:"swap_status,omitempty"`
	// 개별 leg 의 MarkConsumed 결과. swap_status=OK 면 둘 다 OK.
	// partial race (한 leg 만 표시됨) 발생 시 호출자 (매매 AP) 가 거래 거부.
	Near          *MarkConsumedResponse `protobuf:"bytes,2,opt,name=near,proto3" json:"near,omitempty"`
	Far           *MarkConsumedResponse `protobuf:"bytes,3,opt,name=far,proto3" json:"far,omitempty"`
	OrdRejReason  int32                 `protobuf:"varint,4,opt,name=ord_rej_reason,json=ordRejReason,proto3" json:"ord_rej_reason,omitempty"`
	RejectText    string                `protobuf:"bytes,5,opt,name=reject_text,json=rejectText,proto3" json:"reject_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsumeSwapResponse) Reset() {
	*x = ConsumeSwapResponse{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeSwapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeSwapResponse) ProtoMessage() {}

func (x *ConsumeSwapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeSwapResponse.ProtoReflect.Descriptor instead.
func (*ConsumeSwapResponse) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{12}
}

func (x *ConsumeSwapResponse) GetSwapStatus() ValidationStatus {
	if x != nil {
		return x.SwapStatus
	}
	return ValidationStatus_STATUS_UNSPECIFIED
}

func (x *ConsumeSwapResponse) GetNear() *MarkConsumedResponse {
	if x != nil {
		return x.Near
	}
	return nil
}

func (x *ConsumeSwapResponse) GetFar() *MarkConsumedResponse {
	if x != nil {
		return x.Far
	}
	return nil
}

func (x *ConsumeSwapResponse) GetOrdRejReason() int32 {
	if x != nil {
		return x.OrdRejReason
	}
	return 0
}

func (x *ConsumeSwapResponse) GetRejectText() string {
	if x != nil {
		return x.RejectText
	}
	return ""
}

// QuoteRecord 는 pkg/quoteid.Record 의 wire 표현.
type QuoteRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	QuoteId            string                 `protobuf:"bytes,1,opt,name=quote_id,json=quoteId,proto3" json:"quote_id,omitempty"`
	Pair               string                 `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	Channel            string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"` // session.Channel
	Site               string                 `protobuf:"bytes,4,opt,name=site,proto3" json:"site,omitempty"`       // session.Site
	Tier               string                 `protobuf:"bytes,5,opt,name=tier,proto3" json:"tier,omitempty"`       // session.Tier
	Tenor              string                 `protobuf:"bytes,6,opt,name=tenor,proto3" json:"tenor,omitempty"`     // "SPOT" / "1W" / "1M" ...
	Bid                float64                `protobuf:"fixed64,7,opt,name=bid,proto3" json:"bid,omitempty"`
	Ask                float64                `protobuf:"fixed64,8,opt,name=ask,proto3" json:"ask,omitempty"`
	IssuedUnixNano     int64                  `protobuf:"varint,9,opt,name=issued_unix_nano,json=issuedUnixNano,proto3" json:"issued_unix_nano,omitempty"`
	ValidUntilUnixNano int64                  `protobuf:"varint,10,opt,name=valid_until_unix_nano,json=validUntilUnixNano,proto3" json:"valid_until_unix_nano,omitempty"`
	Sequence           uint64                 `protobuf:"varint,11,opt,name=sequence,proto3" json:"sequence,omitempty"` // 인스턴스별 monotonic (FIX MsgSeqNum 동치)
	Issuer             string                 `protobuf:"bytes,12,opt,name=issuer,proto3" json:"issuer,omitempty"`      // mci-price 인스턴스 prefix ("A" / "B")
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QuoteRecord) Reset() {
	*x = QuoteRecord{}
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteRecord) ProtoMessage() {}

func (x *QuoteRecord) ProtoReflect() protoreflect.Message {
	mi := &file_wtg_v1_quote_validation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteRecord.ProtoReflect.Descriptor instead.
func (*QuoteRecord) Descriptor() ([]byte, []int) {
	return file_wtg_v1_quote_validation_proto_rawDescGZIP(), []int{13}
}

func (x *QuoteRecord) GetQuoteId() string {
	if x != nil {
		return x.QuoteId
	}
	return ""
}

func (x *QuoteRecord) GetPair() string {
	if x != nil {
		return x.Pair
	}
	return ""
}

func (x *QuoteRecord) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *QuoteRecord) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *QuoteRecord) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *QuoteRecord) GetTenor() string {
	if x != nil {
		return x.Tenor
	}
	return ""
}

func (x *QuoteRecord) GetBid() float64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *QuoteRecord) GetAsk() float64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *QuoteRecord) GetIssuedUnixNano() int64 {
	if x != nil {
		return x.IssuedUnixNano
	}
	return 0
}

func (x *QuoteRecord) GetValidUntilUnixNano() int64 {
	if x != nil {
		return x.ValidUntilUnixNano
	}
	return 0
}

func (x *QuoteRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *QuoteRecord) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

var File_wtg_v1_quote_validation_proto protoreflect.FileDescriptor

const file_wtg_v1_quote_validation_proto_rawDesc = "" +
	"\n" +
	"\x1dwtg/v1/quote_validation.proto\x12\x06wtg.v1\"k\n" +
	"\x0fValidateRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x1b\n" +
	"\tengine_id\x18\n" +
	" \x01(\tR\bengineId\x12 \n" +
	"\fts_unix_nano\x18\v \x01(\x03R\n" +
	"tsUnixNano\"\xb8\x01\n" +
	"\x10ValidateResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.wtg.v1.ValidationStatusR\x06status\x12+\n" +
	"\x06record\x18\x02 \x01(\v2\x13.wtg.v1.QuoteRecordR\x06record\x12$\n" +
	"\x0eord_rej_reason\x18\x03 \x01(\x05R\fordRejReason\x12\x1f\n" +
	"\vreject_text\x18\x04 \x01(\tR\n" +
	"rejectText\"\x90\x01\n" +
	"\x13MarkConsumedRequest\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12\x1b\n" +
	"\tengine_id\x18\n" +
	" \x01(\tR\bengineId\x12 \n" +
	"\fts_unix_nano\x18\v \x01(\x03R\n" +
	"tsUnixNano\"r\n" +
	"\x14BatchValidateRequest\x12\x1b\n" +
	"\tquote_ids\x18\x01 \x03(\tR\bquoteIds\x12\x1b\n" +
	"\tengine_id\x18\n" +
	" \x01(\tR\bengineId\x12 \n" +
	"\fts_unix_nano\x18\v \x01(\x03R\n" +
	"tsUnixNano\"K\n" +
	"\x15BatchValidateResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.wtg.v1.ValidateResponseR\aresults\"I\n" +
	"\vConsumeItem\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\"\x84\x01\n" +
	"\x18BatchMarkConsumedRequest\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.wtg.v1.ConsumeItemR\x05items\x12\x1b\n" +
	"\tengine_id\x18\n" +
	" \x01(\tR\bengineId\x12 \n" +
	"\fts_unix_nano\x18\v \x01(\x03R\n" +
	"tsUnixNano\"S\n" +
	"\x19BatchMarkConsumedResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.wtg.v1.MarkConsumedResponseR\aresults\"\xdd\x01\n" +
	"\x14MarkConsumedResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.wtg.v1.ValidationStatusR\x06status\x12+\n" +
	"\x06record\x18\x02 \x01(\v2\x13.wtg.v1.QuoteRecordR\x06record\x12\x1f\n" +
	"\vconsumed_by\x18\x03 \x01(\tR\n" +
	"consumedBy\x12$\n" +
	"\x0eord_rej_reason\x18\x04 \x01(\x05R\fordRejReason\x12\x1f\n" +
	"\vreject_text\x18\x05 \x01(\tR\n" +
	"rejectText\"m\n" +
	"\x13ValidateSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12\x1b\n" +
	"\tengine_id\x18\n" +
	" \x01(\tR\bengineId\x12 \n" +
	"\fts_unix_nano\x18\v \x01(\x03R\n" +
	"tsUnixNano\"\xf2\x01\n" +
	"\x14ValidateSwapResponse\x129\n" +
	"\vswap_status\x18\x01 \x01(\x0e2\x18.wtg.v1.ValidationStatusR\n" +
	"swapStatus\x12,\n" +
	"\x04near\x18\x02 \x01(\v2\x18.wtg.v1.ValidateResponseR\x04near\x12*\n" +
	"\x03far\x18\x03 \x01(\v2\x18.wtg.v1.ValidateResponseR\x03far\x12$\n" +
	"\x0eord_rej_reason\x18\x04 \x01(\x05R\fordRejReason\x12\x1f\n" +
	"\vreject_text\x18\x05 \x01(\tR\n" +
	"rejectText\"\x8d\x01\n" +
	"\x12ConsumeSwapRequest\x12\x17\n" +
	"\aswap_id\x18\x01 \x01(\tR\x06swapId\x12\x1f\n" +
	"\vconsumer_id\x18\x02 \x01(\tR\n" +
	"consumerId\x12\x1b\n" +
	"\tengine_id\x18\n" +
	" \x01(\tR\bengineId\x12 \n" +
	"\fts_unix_nano\x18\v \x01(\x03R\n" +
	"tsUnixNano\"\xf9\x01\n" +
	"\x13ConsumeSwapResponse\x129\n" +
	"\vswap_status\x18\x01 \x01(\x0e2\x18.wtg.v1.ValidationStatusR\n" +
	"swapStatus\x120\n" +
	"\x04near\x18\x02 \x01(\v2\x1c.wtg.v1.MarkConsumedResponseR\x04near\x12.\n" +
	"\x03far\x18\x03 \x01(\v2\x1c.wtg.v1.MarkConsumedResponseR\x03far\x12$\n" +
	"\x0eord_rej_reason\x18\x04 \x01(\x05R\fordRejReason\x12\x1f\n" +
	"\vreject_text\x18\x05 \x01(\tR\n" +
	"rejectText\"\xc9\x02\n" +
	"\vQuoteRecord\x12\x19\n" +
	"\bquote_id\x18\x01 \x01(\tR\aquoteId\x12\x12\n" +
	"\x04pair\x18\x02 \x01(\tR\x04pair\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\x12\x12\n" +
	"\x04site\x18\x04 \x01(\tR\x04site\x12\x12\n" +
	"\x04tier\x18\x05 \x01(\tR\x04tier\x12\x14\n" +
	"\x05tenor\x18\x06 \x01(\tR\x05tenor\x12\x10\n" +
	"\x03bid\x18\a \x01(\x01R\x03bid\x12\x10\n" +
	"\x03ask\x18\b \x01(\x01R\x03ask\x12(\n" +
	"\x10issued_unix_nano\x18\t \x01(\x03R\x0eissuedUnixNano\x121\n" +
	"\x15valid_until_unix_nano\x18\n" +
	" \x01(\x03R\x12validUntilUnixNano\x12\x1a\n" +
	"\bsequence\x18\v \x01(\x04R\bsequence\x12\x16\n" +
	"\x06issuer\x18\f \x01(\tR\x06issuer*d\n" +
	"\x10ValidationStatus\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02OK\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\v\n" +
	"\aEXPIRED\x10\x03\x12\x14\n" +
	"\x10ALREADY_CONSUMED\x10\x042\xdd\x03\n" +
	"\x16QuoteValidationService\x12=\n" +
	"\bValidate\x12\x17.wtg.v1.ValidateRequest\x1a\x18.wtg.v1.ValidateResponse\x12I\n" +
	"\fMarkConsumed\x12\x1b.wtg.v1.MarkConsumedRequest\x1a\x1c.wtg.v1.MarkConsumedResponse\x12L\n" +
	"\rBatchValidate\x12\x1c.wtg.v1.BatchValidateRequest\x1a\x1d.wtg.v1.BatchValidateResponse\x12X\n" +
	"\x11BatchMarkConsumed\x12 .wtg.v1.BatchMarkConsumedRequest\x1a!.wtg.v1.BatchMarkConsumedResponse\x12I\n" +
	"\fValidateSwap\x12\x1b.wtg.v1.ValidateSwapRequest\x1a\x1c.wtg.v1.ValidateSwapResponse\x12F\n" +
	"\vConsumeSwap\x12\x1a.wtg.v1.ConsumeSwapRequest\x1a\x1b.wtg.v1.ConsumeSwapResponseB3Z1github.com/winwaysystems/wtg/pkg/wtgpb/v1;wtgpbv1b\x06proto3"

var (
	file_wtg_v1_quote_validation_proto_rawDescOnce sync.Once
	file_wtg_v1_quote_validation_proto_rawDescData []byte
)

func file_wtg_v1_quote_validation_proto_rawDescGZIP() []byte {
	file_wtg_v1_quote_validation_proto_rawDescOnce.Do(func() {
		file_wtg_v1_quote_validation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_wtg_v1_quote_validation_proto_rawDesc), len(file_wtg_v1_quote_validation_proto_rawDesc)))
	})
	return file_wtg_v1_quote_validation_proto_rawDescData
}

var file_wtg_v1_quote_validation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_wtg_v1_quote_validation_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_wtg_v1_quote_validation_proto_goTypes = []any{
	(ValidationStatus)(0),             // 0: wtg.v1.ValidationStatus
	(*ValidateRequest)(nil),           // 1: wtg.v1.ValidateRequest
	(*ValidateResponse)(nil),          // 2: wtg.v1.ValidateResponse
	(*MarkConsumedRequest)(nil),       // 3: wtg.v1.MarkConsumedRequest
	(*BatchValidateRequest)(nil),      // 4: wtg.v1.BatchValidateRequest
	(*BatchValidateResponse)(nil),     // 5: wtg.v1.BatchValidateResponse
	(*ConsumeItem)(nil),               // 6: wtg.v1.ConsumeItem
	(*BatchMarkConsumedRequest)(nil),  // 7: wtg.v1.BatchMarkConsumedRequest
	(*BatchMarkConsumedResponse)(nil), // 8: wtg.v1.BatchMarkConsumedResponse
	(*MarkConsumedResponse)(nil),      // 9: wtg.v1.MarkConsumedResponse
	(*ValidateSwapRequest)(nil),       // 10: wtg.v1.ValidateSwapRequest
	(*ValidateSwapResponse)(nil),      // 11: wtg.v1.ValidateSwapResponse
	(*ConsumeSwapRequest)(nil),        // 12: wtg.v1.ConsumeSwapRequest
	(*ConsumeSwapResponse)(nil),       // 13: wtg.v1.ConsumeSwapResponse
	(*QuoteRecord)(nil),               // 14: wtg.v1.QuoteRecord
}
var file_wtg_v1_quote_validation_proto_depIdxs = []int32{
	0,  // 0: wtg.v1.ValidateResponse.status:type_name -> wtg.v1.ValidationStatus
	14, // 1: wtg.v1.ValidateResponse.record:type_name -> wtg.v1.QuoteRecord
	2,  // 2: wtg.v1.BatchValidateResponse.results:type_name -> wtg.v1.ValidateResponse
	6,  // 3: wtg.v1.BatchMarkConsumedRequest.items:type_name -> wtg.v1.ConsumeItem
	9,  // 4: wtg.v1.BatchMarkConsumedResponse.results:type_name -> wtg.v1.MarkConsumedResponse
	0,  // 5: wtg.v1.MarkConsumedResponse.status:type_name -> wtg.v1.ValidationStatus
	14, // 6: wtg.v1.MarkConsumedResponse.record:type_name -> wtg.v1.QuoteRecord
	0,  // 7: wtg.v1.ValidateSwapResponse.swap_status:type_name -> wtg.v1.ValidationStatus
	2,  // 8: wtg.v1.ValidateSwapResponse.near:type_name -> wtg.v1.ValidateResponse
	2,  // 9: wtg.v1.ValidateSwapResponse.far:type_name -> wtg.v1.ValidateResponse
	0,  // 10: wtg.v1.ConsumeSwapResponse.swap_status:type_name -> wtg.v1.ValidationStatus
	9,  // 11: wtg.v1.ConsumeSwapResponse.near:type_name -> wtg.v1.MarkConsumedResponse
	9,  // 12: wtg.v1.ConsumeSwapResponse.far:type_name -> wtg.v1.MarkConsumedResponse
	1,  // 13: wtg.v1.QuoteValidationService.Validate:input_type -> wtg.v1.ValidateRequest
	3,  // 14: wtg.v1.QuoteValidationService.MarkConsumed:input_type -> wtg.v1.MarkConsumedRequest
	4,  // 15: wtg.v1.QuoteValidationService.BatchValidate:input_type -> wtg.v1.BatchValidateRequest
	7,  // 16: wtg.v1.QuoteValidationService.BatchMarkConsumed:input_type -> wtg.v1.BatchMarkConsumedRequest
	10, // 17: wtg.v1.QuoteValidationService.ValidateSwap:input_type -> wtg.v1.ValidateSwapRequest
	12, // 18: wtg.v1.QuoteValidationService.ConsumeSwap:input_type -> wtg.v1.ConsumeSwapRequest
	2,  // 19: wtg.v1.QuoteValidationService.Validate:output_type -> wtg.v1.ValidateResponse
	9,  // 20: wtg.v1.QuoteValidationService.MarkConsumed:output_type -> wtg.v1.MarkConsumedResponse
	5,  // 21: wtg.v1.QuoteValidationService.BatchValidate:output_type -> wtg.v1.BatchValidateResponse
	8,  // 22: wtg.v1.QuoteValidationService.BatchMarkConsumed:output_type -> wtg.v1.BatchMarkConsumedResponse
	11, // 23: wtg.v1.QuoteValidationService.ValidateSwap:output_type -> wtg.v1.ValidateSwapResponse
	13, // 24: wtg.v1.QuoteValidationService.ConsumeSwap:output_type -> wtg.v1.ConsumeSwapResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_wtg_v1_quote_validation_proto_init() }
func file_wtg_v1_quote_validation_proto_init() {
	if File_wtg_v1_quote_validation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_wtg_v1_quote_validation_proto_rawDesc), len(file_wtg_v1_quote_validation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_wtg_v1_quote_validation_proto_goTypes,
		DependencyIndexes: file_wtg_v1_quote_validation_proto_depIdxs,
		EnumInfos:         file_wtg_v1_quote_validation_proto_enumTypes,
		MessageInfos:      file_wtg_v1_quote_validation_proto_msgTypes,
	}.Build()
	File_wtg_v1_quote_validation_proto = out.File
	file_wtg_v1_quote_validation_proto_goTypes = nil
	file_wtg_v1_quote_validation_proto_depIdxs = nil
}
