// QuoteValidationService — 매칭 엔진이 NewOrderSingle (FIX 'D') 의 QuoteID
// (FIX 4.4 tag 117) 를 검증하기 위해 호출하는 RPC.
//
// 설계 / 정책 분담 / 호출 흐름은 docs/quoteid-validation-rfc.md 참조.
//
// 정합성:
//   FIX 4.4    — tag 117 (QuoteID), tag 62 (ValidUntilTime), tag 103 (OrdRejReason)
//   FX Global Code 2024 Principle 17 — last-look 투명성
//   MiFID II RTS 27 — best-execution audit trail

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: wtg/v1/quote_validation.proto

package wtgpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuoteValidationService_Validate_FullMethodName = "/wtg.v1.QuoteValidationService/Validate"
)

// QuoteValidationServiceClient is the client API for QuoteValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteValidationServiceClient interface {
	// Validate 는 QuoteID 의 권위 데이터를 조회한다.
	//
	// WTG (mci-price) 가 담당:
	//   - 존재 여부 (NOT_FOUND)
	//   - 만료 여부 (EXPIRED — ValidUntil + grace 도래 후)
	//   - 발행 시점 가격 / Profile / Issuer echo
	//
	// 엔진이 담당 (본 RPC 의 응답 + 엔진 자체 정책):
	//   - side validation (FIX tag 54: BUY=ask vs SELL=bid)
	//   - slippage tolerance (tier별)
	//   - last-look hold-time (FX Global Code Principle 17, tier별)
	//   - 사용자 ↔ Profile 일치
	//   - 잔량 / 한도
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
}

type quoteValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteValidationServiceClient(cc grpc.ClientConnInterface) QuoteValidationServiceClient {
	return &quoteValidationServiceClient{cc}
}

func (c *quoteValidationServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, QuoteValidationService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteValidationServiceServer is the server API for QuoteValidationService service.
// All implementations must embed UnimplementedQuoteValidationServiceServer
// for forward compatibility.
type QuoteValidationServiceServer interface {
	// Validate 는 QuoteID 의 권위 데이터를 조회한다.
	//
	// WTG (mci-price) 가 담당:
	//   - 존재 여부 (NOT_FOUND)
	//   - 만료 여부 (EXPIRED — ValidUntil + grace 도래 후)
	//   - 발행 시점 가격 / Profile / Issuer echo
	//
	// 엔진이 담당 (본 RPC 의 응답 + 엔진 자체 정책):
	//   - side validation (FIX tag 54: BUY=ask vs SELL=bid)
	//   - slippage tolerance (tier별)
	//   - last-look hold-time (FX Global Code Principle 17, tier별)
	//   - 사용자 ↔ Profile 일치
	//   - 잔량 / 한도
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	mustEmbedUnimplementedQuoteValidationServiceServer()
}

// UnimplementedQuoteValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuoteValidationServiceServer struct{}

func (UnimplementedQuoteValidationServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedQuoteValidationServiceServer) mustEmbedUnimplementedQuoteValidationServiceServer() {
}
func (UnimplementedQuoteValidationServiceServer) testEmbeddedByValue() {}

// UnsafeQuoteValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteValidationServiceServer will
// result in compilation errors.
type UnsafeQuoteValidationServiceServer interface {
	mustEmbedUnimplementedQuoteValidationServiceServer()
}

func RegisterQuoteValidationServiceServer(s grpc.ServiceRegistrar, srv QuoteValidationServiceServer) {
	// If the following call panics, it indicates UnimplementedQuoteValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuoteValidationService_ServiceDesc, srv)
}

func _QuoteValidationService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteValidationServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteValidationService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteValidationServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteValidationService_ServiceDesc is the grpc.ServiceDesc for QuoteValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wtg.v1.QuoteValidationService",
	HandlerType: (*QuoteValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _QuoteValidationService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wtg/v1/quote_validation.proto",
}
