// QuoteValidationService — 매칭 엔진이 NewOrderSingle (FIX 'D') 의 QuoteID
// (FIX 4.4 tag 117) 를 검증하기 위해 호출하는 RPC.
//
// 설계 / 정책 분담 / 호출 흐름은 docs/quoteid-validation-rfc.md 참조.
//
// 정합성:
//   FIX 4.4    — tag 117 (QuoteID), tag 62 (ValidUntilTime), tag 103 (OrdRejReason)
//   FX Global Code 2024 Principle 17 — last-look 투명성
//   MiFID II RTS 27 — best-execution audit trail

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: wtg/v1/quote_validation.proto

package wtgpbv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QuoteValidationService_Validate_FullMethodName          = "/wtg.v1.QuoteValidationService/Validate"
	QuoteValidationService_MarkConsumed_FullMethodName      = "/wtg.v1.QuoteValidationService/MarkConsumed"
	QuoteValidationService_BatchValidate_FullMethodName     = "/wtg.v1.QuoteValidationService/BatchValidate"
	QuoteValidationService_BatchMarkConsumed_FullMethodName = "/wtg.v1.QuoteValidationService/BatchMarkConsumed"
)

// QuoteValidationServiceClient is the client API for QuoteValidationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QuoteValidationServiceClient interface {
	// Validate 는 QuoteID 의 권위 데이터를 read-only 로 조회한다. 멱등 — 같은
	// QuoteID 를 여러 번 호출해도 동일 결과.
	//
	// WTG (mci-price) 가 담당:
	//   - 존재 여부 (NOT_FOUND)
	//   - 만료 여부 (EXPIRED — ValidUntil + grace 도래 후)
	//   - 사용 여부 (ALREADY_CONSUMED — 다른 주문이 이미 체결에 사용)
	//   - 발행 시점 가격 / Profile / Issuer echo
	//
	// 엔진이 담당 (본 RPC 의 응답 + 엔진 자체 정책):
	//   - side validation (FIX tag 54: BUY=ask vs SELL=bid)
	//   - slippage tolerance (tier별)
	//   - last-look hold-time (FX Global Code Principle 17, tier별)
	//   - 사용자 ↔ Profile 일치
	//   - 잔량 / 한도
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error)
	// MarkConsumed 는 QuoteID 의 "사용 완료" 를 원자적으로 표시한다.
	//
	// FX Global Code Principle 17 의 "use only once" 정합 — 한 QuoteID 는
	// 단 한 번의 체결에 묶여야 한다 (replay 방지). EBS Direct / LMAX / CME FX
	// 모두 server-side consumption tracking.
	//
	// 엔진 흐름:
	//  1. Validate(quote_id) → OK + record
	//  2. 자체 정책 검사 (slippage / side / 한도)
	//  3. MarkConsumed(quote_id, consumer="order-N")
	//     - result == OK         → 체결 진행
	//     - result == ALREADY_CONSUMED → 동시에 다른 주문이 잡음, 거절
	//     - result == NOT_FOUND  → record GC 됨 (드물게 race)
	//     - result == EXPIRED    → ValidUntil 도래, 체결 불가
	//  4. 체결 후 ExecutionReport.
	//
	// 원자성: Memory 는 mutex, Redis 는 SET NX. 두 mci-price 가 동시에 같은
	// QuoteID 에 대해 MarkConsumed 받아도 정확히 한 호출만 OK.
	MarkConsumed(ctx context.Context, in *MarkConsumedRequest, opts ...grpc.CallOption) (*MarkConsumedResponse, error)
	// BatchValidate 는 여러 QuoteID 를 단일 RPC 로 검증. 결과는 입력과 같은
	// 순서의 배열로 반환 (results[i] == quote_ids[i] 의 결과).
	//
	// 사용 시나리오:
	//   - 다건 주문 (FIX NewOrderList 'E') 의 전체 사전 검증.
	//   - 감사 / 재계산 잡의 bulk lookup.
	//
	// 서버는 goroutine fan-out 으로 병렬 처리 — N=100 batch 가 단일 Validate
	// 와 비슷한 wallclock 으로 끝남. batch 크기 상한은 1000 (운영 abuse 방어).
	BatchValidate(ctx context.Context, in *BatchValidateRequest, opts ...grpc.CallOption) (*BatchValidateResponse, error)
	// BatchMarkConsumed — 여러 (quote_id, consumer_id) 쌍을 한 RPC 로 표시.
	// 각 항목은 독립적으로 atomic (Memory mutex / Redis SET NX) — partial 결과
	// 가능 (일부 OK, 일부 ALREADY_CONSUMED). 결과는 입력 순서와 동일한 배열.
	//
	// FIX NewOrderList ('E') 다건 주문 fill 직전 한 번에 표시 — 직렬 호출
	// 대비 N× wallclock 개선 (goroutine fan-out 으로 Redis round-trip 병렬화).
	BatchMarkConsumed(ctx context.Context, in *BatchMarkConsumedRequest, opts ...grpc.CallOption) (*BatchMarkConsumedResponse, error)
}

type quoteValidationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQuoteValidationServiceClient(cc grpc.ClientConnInterface) QuoteValidationServiceClient {
	return &quoteValidationServiceClient{cc}
}

func (c *quoteValidationServiceClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*ValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateResponse)
	err := c.cc.Invoke(ctx, QuoteValidationService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteValidationServiceClient) MarkConsumed(ctx context.Context, in *MarkConsumedRequest, opts ...grpc.CallOption) (*MarkConsumedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkConsumedResponse)
	err := c.cc.Invoke(ctx, QuoteValidationService_MarkConsumed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteValidationServiceClient) BatchValidate(ctx context.Context, in *BatchValidateRequest, opts ...grpc.CallOption) (*BatchValidateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchValidateResponse)
	err := c.cc.Invoke(ctx, QuoteValidationService_BatchValidate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *quoteValidationServiceClient) BatchMarkConsumed(ctx context.Context, in *BatchMarkConsumedRequest, opts ...grpc.CallOption) (*BatchMarkConsumedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchMarkConsumedResponse)
	err := c.cc.Invoke(ctx, QuoteValidationService_BatchMarkConsumed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QuoteValidationServiceServer is the server API for QuoteValidationService service.
// All implementations must embed UnimplementedQuoteValidationServiceServer
// for forward compatibility.
type QuoteValidationServiceServer interface {
	// Validate 는 QuoteID 의 권위 데이터를 read-only 로 조회한다. 멱등 — 같은
	// QuoteID 를 여러 번 호출해도 동일 결과.
	//
	// WTG (mci-price) 가 담당:
	//   - 존재 여부 (NOT_FOUND)
	//   - 만료 여부 (EXPIRED — ValidUntil + grace 도래 후)
	//   - 사용 여부 (ALREADY_CONSUMED — 다른 주문이 이미 체결에 사용)
	//   - 발행 시점 가격 / Profile / Issuer echo
	//
	// 엔진이 담당 (본 RPC 의 응답 + 엔진 자체 정책):
	//   - side validation (FIX tag 54: BUY=ask vs SELL=bid)
	//   - slippage tolerance (tier별)
	//   - last-look hold-time (FX Global Code Principle 17, tier별)
	//   - 사용자 ↔ Profile 일치
	//   - 잔량 / 한도
	Validate(context.Context, *ValidateRequest) (*ValidateResponse, error)
	// MarkConsumed 는 QuoteID 의 "사용 완료" 를 원자적으로 표시한다.
	//
	// FX Global Code Principle 17 의 "use only once" 정합 — 한 QuoteID 는
	// 단 한 번의 체결에 묶여야 한다 (replay 방지). EBS Direct / LMAX / CME FX
	// 모두 server-side consumption tracking.
	//
	// 엔진 흐름:
	//  1. Validate(quote_id) → OK + record
	//  2. 자체 정책 검사 (slippage / side / 한도)
	//  3. MarkConsumed(quote_id, consumer="order-N")
	//     - result == OK         → 체결 진행
	//     - result == ALREADY_CONSUMED → 동시에 다른 주문이 잡음, 거절
	//     - result == NOT_FOUND  → record GC 됨 (드물게 race)
	//     - result == EXPIRED    → ValidUntil 도래, 체결 불가
	//  4. 체결 후 ExecutionReport.
	//
	// 원자성: Memory 는 mutex, Redis 는 SET NX. 두 mci-price 가 동시에 같은
	// QuoteID 에 대해 MarkConsumed 받아도 정확히 한 호출만 OK.
	MarkConsumed(context.Context, *MarkConsumedRequest) (*MarkConsumedResponse, error)
	// BatchValidate 는 여러 QuoteID 를 단일 RPC 로 검증. 결과는 입력과 같은
	// 순서의 배열로 반환 (results[i] == quote_ids[i] 의 결과).
	//
	// 사용 시나리오:
	//   - 다건 주문 (FIX NewOrderList 'E') 의 전체 사전 검증.
	//   - 감사 / 재계산 잡의 bulk lookup.
	//
	// 서버는 goroutine fan-out 으로 병렬 처리 — N=100 batch 가 단일 Validate
	// 와 비슷한 wallclock 으로 끝남. batch 크기 상한은 1000 (운영 abuse 방어).
	BatchValidate(context.Context, *BatchValidateRequest) (*BatchValidateResponse, error)
	// BatchMarkConsumed — 여러 (quote_id, consumer_id) 쌍을 한 RPC 로 표시.
	// 각 항목은 독립적으로 atomic (Memory mutex / Redis SET NX) — partial 결과
	// 가능 (일부 OK, 일부 ALREADY_CONSUMED). 결과는 입력 순서와 동일한 배열.
	//
	// FIX NewOrderList ('E') 다건 주문 fill 직전 한 번에 표시 — 직렬 호출
	// 대비 N× wallclock 개선 (goroutine fan-out 으로 Redis round-trip 병렬화).
	BatchMarkConsumed(context.Context, *BatchMarkConsumedRequest) (*BatchMarkConsumedResponse, error)
	mustEmbedUnimplementedQuoteValidationServiceServer()
}

// UnimplementedQuoteValidationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQuoteValidationServiceServer struct{}

func (UnimplementedQuoteValidationServiceServer) Validate(context.Context, *ValidateRequest) (*ValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedQuoteValidationServiceServer) MarkConsumed(context.Context, *MarkConsumedRequest) (*MarkConsumedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkConsumed not implemented")
}
func (UnimplementedQuoteValidationServiceServer) BatchValidate(context.Context, *BatchValidateRequest) (*BatchValidateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchValidate not implemented")
}
func (UnimplementedQuoteValidationServiceServer) BatchMarkConsumed(context.Context, *BatchMarkConsumedRequest) (*BatchMarkConsumedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchMarkConsumed not implemented")
}
func (UnimplementedQuoteValidationServiceServer) mustEmbedUnimplementedQuoteValidationServiceServer() {
}
func (UnimplementedQuoteValidationServiceServer) testEmbeddedByValue() {}

// UnsafeQuoteValidationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QuoteValidationServiceServer will
// result in compilation errors.
type UnsafeQuoteValidationServiceServer interface {
	mustEmbedUnimplementedQuoteValidationServiceServer()
}

func RegisterQuoteValidationServiceServer(s grpc.ServiceRegistrar, srv QuoteValidationServiceServer) {
	// If the following call panics, it indicates UnimplementedQuoteValidationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QuoteValidationService_ServiceDesc, srv)
}

func _QuoteValidationService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteValidationServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteValidationService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteValidationServiceServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteValidationService_MarkConsumed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkConsumedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteValidationServiceServer).MarkConsumed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteValidationService_MarkConsumed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteValidationServiceServer).MarkConsumed(ctx, req.(*MarkConsumedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteValidationService_BatchValidate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteValidationServiceServer).BatchValidate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteValidationService_BatchValidate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteValidationServiceServer).BatchValidate(ctx, req.(*BatchValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QuoteValidationService_BatchMarkConsumed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchMarkConsumedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QuoteValidationServiceServer).BatchMarkConsumed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QuoteValidationService_BatchMarkConsumed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QuoteValidationServiceServer).BatchMarkConsumed(ctx, req.(*BatchMarkConsumedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QuoteValidationService_ServiceDesc is the grpc.ServiceDesc for QuoteValidationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QuoteValidationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wtg.v1.QuoteValidationService",
	HandlerType: (*QuoteValidationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _QuoteValidationService_Validate_Handler,
		},
		{
			MethodName: "MarkConsumed",
			Handler:    _QuoteValidationService_MarkConsumed_Handler,
		},
		{
			MethodName: "BatchValidate",
			Handler:    _QuoteValidationService_BatchValidate_Handler,
		},
		{
			MethodName: "BatchMarkConsumed",
			Handler:    _QuoteValidationService_BatchMarkConsumed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "wtg/v1/quote_validation.proto",
}
